### ISSUE TITLE
Verify this with sysadmins

### ISSUE THREAD

**Issue by Forceflow** [Wout12345/anet#1]
Hey there, ex-CS student here :)

This looks cool, but it might be a good idea (if you haven't already done so) to verify usage of this with the CS sysadmins. I vaguely recall there being some problems with students automating stuff that caused issues, although it was probably crypto mining back then. 

Good luck with the project, and feel free to ignore this if this is already vetted!

**Comment by Wout12345** [comment]
Hello, also an ex-CS student and now PhD student here. ;-)

In all honesty, when I wrote this as a student, I deliberately didn't try to get the system group involved too much, since they didn't seem to like me not using SSH the way it's intended at the department ... However, a friend recently checked in with them and apparently they thought it sounded like a fun project, so all is actually fine. :) I still updated the README a bit with some better security advice involving the use of ssh-agent.

As for abuse, of course, I don't know what people are doing with this project. I wrote it for my computer graphics project, then a friend asked me for the code next year when taking the same course, followed by one or two other master students ... therefore I just quickly threw it online in this repository. In short, I don't think many people are using it. ;-) In any case, I haven't received any complaints about abuse in the meantime, so I don't think it has caused any noticeable problems so far.
